### ISSUE TITLE
continuous.py fails when disturbance is set to none

### ISSUE THREAD

**Issue by necozay** [tulip-control/tulip-control#101]
When I set `E=None` and `W=None` in `continuous.py`, it gives the following error:

```execfile('continuousNodisy.py')
No handlers could be found for logger "tulip.transys.export.graph2dot"
Total abstraction time: 36.63[sec]
Constructing and playing the game...
Games time: 21
Checking realizability time: 22
Specification is realizable.
Building an implementation...
Automaton is written in /tmp/tmpkI1RW2
Strategy time: 18
===== Done ==================================

Automaton successfully synthesized.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "continuousNodisy.py", line 104, in <module>
    sys=disc_dynamics.ts, ignore_sys_init=True)
  File "/usr/local/lib/python2.7/dist-packages/tulip-1.1a_dev_9953a1079cb84d5985d6102110e6cc1b36fcc1b0-py2.7.egg/tulip/synth.py", line 1162, in synthesize
    ctrl = jtlv.synthesize(specs)
  File "/usr/local/lib/python2.7/dist-packages/tulip-1.1a_dev_9953a1079cb84d5985d6102110e6cc1b36fcc1b0-py2.7.egg/tulip/interfaces/jtlv.py", line 177, in synthesize
    aut = load_file(fAUT, spec)
  File "/usr/local/lib/python2.7/dist-packages/tulip-1.1a_dev_9953a1079cb84d5985d6102110e6cc1b36fcc1b0-py2.7.egg/tulip/interfaces/jtlv.py", line 503, in load_file
    t = spec.evaluate(bool_values)
  File "/usr/local/lib/python2.7/dist-packages/tulip-1.1a_dev_9953a1079cb84d5985d6102110e6cc1b36fcc1b0-py2.7.egg/tulip/spec/form.py", line 681, in evaluate
    sys_init = _eval_formula(_conj(cp.sys_init) )
  File "/usr/local/lib/python2.7/dist-packages/tulip-1.1a_dev_9953a1079cb84d5985d6102110e6cc1b36fcc1b0-py2.7.egg/tulip/spec/form.py", line 695, in _eval_formula
    return eval(f)
  File "<string>", line 1, in <module>
NameError: name 'loc' is not defined
```

**Comment by slivingston** [comment]
As of c8f821793035660b910e586cff625092193deb79 (tip of `master` at time of writing), the error still occurs when the JTLV solver is used. Switching to gr1c, as suggested by @johnyf [above](https://github.com/tulip-control/tulip-control/issues/101#issuecomment-53650763), leads to synthesis of a strategy.

I am not sure what is meant by "The issue is resolved..." in [the previous comment](https://github.com/tulip-control/tulip-control/issues/101#issuecomment-53979937) since `examples/robot_planning/continuous.py` still uses the JTLV solver. Nonetheless, the plan is to switch the default GR(1) solver to be different within a few days, so assuming it will be gr1c, we can regard this as issue as closed.
