### ISSUE TITLE
non-deterministic behavior in discretize (or polytope 0.1.2)

### ISSUE THREAD

**Issue by necozay** [tulip-control/tulip-control#161]
Not sure how much of this is a `tulip` issue and how much of it is a `polytope` issue but reporting here.

In the `continuous.py`, when I make the following changes:
```python
input_bound = 10.0
disc_dynamics = discretize(
    cont_partition, sys_dyn, closed_loop=False,
    conservative=True,
    N=5, min_cell_volume=0.1, plotit=show
)
```

`discretize` behaves nondeterministically. It succeeds half of the time and in the other half, it terminates with the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "continuous_test.py", line 74, in <module>
    N=5, min_cell_volume=0.1, plotit=show
  File "/home/necmiye/Public/tulip-control/tulip/abstract/discretization.py", line 649, in discretize
    use_all_horizon, trans_set, max_num_poly
  File "/home/necmiye/Public/tulip-control/tulip/abstract/feasible.py", line 116, in solve_feasible
    max_num_poly=max_num_poly
  File "/home/necmiye/Public/tulip-control/tulip/abstract/feasible.py", line 219, in solve_open_loop
    cur_s0 = poly_to_poly(p1, p2, ssys, N, trans_set)
  File "/home/necmiye/Public/tulip-control/tulip/abstract/feasible.py", line 242, in poly_to_poly
    s0 = s0.project(dims)
  File "/usr/local/lib/python2.7/dist-packages/polytope-0.1.2-py2.7.egg/polytope/polytope.py", line 344, in project
    return projection(self, dim, solver, abs_tol, verbose)
  File "/usr/local/lib/python2.7/dist-packages/polytope-0.1.2-py2.7.egg/polytope/polytope.py", line 1505, in projection
    return projection_iterhull(poly1,new_dim)
  File "/usr/local/lib/python2.7/dist-packages/polytope-0.1.2-py2.7.egg/polytope/polytope.py", line 1729, in projection_iterhull
    raise Exception("iterative_hull: "
Exception: iterative_hull: could not find starting simplex
```

**Comment by necozay** [comment]
Diagnosis: when using `closed_loop = False` with a not too short horizon, the default projection algorithm ends up being iterative hull which is not deterministic: see [this line](https://github.com/tulip-control/polytope/blob/master/polytope/polytope.py#L1732). Increasing the maximum iterations in iterative hull can make it more likely to succeed. Also, we can consider fixing the seed if we want to avoid randomness. Closing the issue as it looks more like a `polytope` issue.
